export const ALL_TICKETS_REQUEST = 'ALL_TICKETS_REQUEST'
export const ALL_TICKETS_SUCCESS = 'ALL_TICKETS_SUCCES'
export const ALL_TICKETS_FAIL = 'ALL_TICKETS_FAIL'

export const USUARIO_DETAIL_REQUEST = 'USUARIO_DETAIL_REQUEST'
export const USUARIO_DETAIL_SUCCESS = 'USUARIO_DETAIL_SUCCESS'
export const USUARIO_DETAIL_FAIL = 'USUARIO_DETAIL_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'